#include "src/defs.h"

ENUM_DEFN_FUNCTIONS(object_type_index, OT, ENUM_OBJECT_TYPE_INDEX)
ENUM_DEFN_FUNCTIONS(decal_type_index, DT, ENUM_DECAL_TYPE_INDEX)
ENUM_DEFN_FUNCTIONS(decal_type_flags, DTF, ENUM_DECAL_TYPE_FLAGS)
ENUM_DEFN_FUNCTIONS(sector_flags, SECTOR_FLAG, ENUM_SECTOR_FLAGS)
ENUM_DEFN_FUNCTIONS(sector_cos_type_index, SCCT, ENUM_SECTOR_COS_TYPE_INDEX)
ENUM_DEFN_FUNCTIONS(sector_func_type_index, SCFT, ENUM_SECTOR_FUNC_TYPE_INDEX)
ENUM_DEFN_FUNCTIONS(side_cos_type_index, SDCT, ENUM_SIDE_COS_TYPE_INDEX)
ENUM_DEFN_FUNCTIONS(side_func_type_index, SDFT, ENUM_SIDE_FUNC_TYPE_INDEX)
ENUM_DEFN_FUNCTIONS(item_type, ITEM_TYPE, ENUM_ITEM_TYPE)
ENUM_DEFN_FUNCTIONS(particle_type_index, PARTICLE_TYPE, ENUM_PARTICLE_TYPE)
